PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX wp: <http://rdf.telegraph.co.uk/ontology/movies-web-publishing-annotations#>



SELECT DISTINCT ?predicateLabel ?property ?classLabel ?objectPredicateLabel ?object2PredicateLabel

WHERE { {
	
?entity			?predicate 		?property .
?predicate 		rdf:type 		owl:DatatypeProperty .
?precicate		wp:publish 		"true"^^xsd:boolean .
?predicate 		rdfs:label 		?predicateLabel .

} UNION {

?entity					?predicate 			?object .
?object 				rdf:type			?class .
?class 					rdfs:label 			?classLabel .
?predicate 				rdf:type			owl:ObjectProperty .
?predicate 				wp:publish 			"true"^^xsd:boolean .
?predicate 				rdfs:label 			?predicateLabel .
?object 				?objectPredicate 	?property .
?objectPredicate 		rdf:type 			owl:DatatypeProperty .
?objectPredicate 		wp:publish 			"true"^^xsd:boolean .
?objectPredicate 		rdfs:label 			?objectPredicateLabel .

} UNION {

?entity				?predicate 			?object .
?predicate 			rdf:type			owl:ObjectProperty .
?predicate 			wp:publish 			"true"^^xsd:boolean .
?object 			?objectPredicate 	?object2 .
?objectPredicate 	rdf:type 			owl:ObjectProperty .
?objectPredicate	wp:publish 			"true"^^xsd:boolean .
?objectPredicate 	rdfs:label 			?predicateLabel .
?object2			?object2Predicate	?property .
?object2 			rdf:type 			?class .
?class 				rdfs:label 			?classLabel .
?object2Predicate	rdf:type			owl:DatatypeProperty .
?object2Predicate	wp:publish 			"true"^^xsd:boolean .
?object2Predicate	rdfs:label 			?object2PredicateLabel


}  }